import { Page } from "page.slint";
import { Button } from "std-widgets.slint";
import { Lang } from "../../lang/lang.slint";
import { Translator,TranslatorData } from "../../lang/translator.slint";
export component HomePage inherits Page {
    in-out property <string> username;
    in-out property <image> user-avatar;
    in-out property <bool> logged-in;
    callback rfd-load-img();
    property <Translator> lang_trans: Lang.translator;
    header: logged-in?lang-trans.login-tips:lang-trans.no-login-tips;
    Button {
        text: logged-in?"Logged out test":"Logged in test";
        clicked => {
            username = logged-in?"":"XSlime";
            TranslatorData.username = username;
            if(!logged-in) {rfd-load-img();}
            logged-in=!logged-in;
        }
    }
}