import { Page } from "page.slint";
import { Slider , Switch, ComboBox} from "std-widgets.slint";

component SettingsOption inherits Rectangle {
    in property <string> option_name: "Title";
    in property <[image]> icons;
    in property <bool> has-icon: true;
    in property <angle> icon-angle: 0deg;
    in property <int> current-icon: 0;
    in-out property <brush> colorize: #000;
    border-color: #77777707;
    border-width: 1px;
    border-radius: 12px;
    background: #77777703;
    padding: 10px;
    height: layout.min-height+self.padding;
    layout:=HorizontalLayout {
        padding: root.padding;
        spacing: 4px;
        VerticalLayout {
            alignment: center;
            Rectangle {
                width: has-icon?14px:0px;
                height: has-icon?14px:0px;
                for icon[index] in icons :
                Image{
                    opacity: current-icon == index?1.0:0.0;
                    rotation-angle: icon-angle;
                    colorize: root.colorize;
                    source: icon;
                    image-fit: contain;
                    height: parent.height;
                    width: parent.width;
                    animate opacity {
                        duration: 75ms;
                        easing: cubic-bezier(0, 0.0, 0.75, 1);
                    }
                }
            }
        }
        option_name:=Text {
            vertical-alignment: center;
            text: root.option-name;
            width: self.min-width;
            font-size: 14px;
            font-weight: 500;
            color: root.colorize;
        }
        Rectangle {
            @children
        }
    }
}

export component SettingsPage inherits Page {
    header: "设置";
    in-out property <bool> dark:false;
    in-out property <brush> option-colorize: #000;
    in-out property <brush> option-border-color: #00000007;
    in-out property <brush> option-bg-color: #00000003;
    in-out property <float> win-opacity:0;
    animate option-bg-color,option-border-color,option-colorize {
        duration: 75ms;
        easing: cubic-bezier(0, 0.0, 0.75, 1);
    }
    VerticalLayout {
        x:0px;
        y:0px;
        spacing: 8px;
        padding-left: -10px;
        padding-right: -10px;
        alignment: start;
        opacity:=SettingsOption {
            colorize: option-colorize;
            has-icon: true;
            icons: [@image-url("../../res/icons/settings/opacity.svg")];
            option-name: "透明度";
            icon-angle: 225deg;
            border-color: option-border-color;
            background: option-bg-color;
            HorizontalLayout {
                alignment: end;
                Slider {
                    width: 125px;
                    minimum: 20;
                    value: 100;
                    changed => {
                        root.win-opacity = self.value / self.maximum;
                    }
                }
            }
        }
        themes:=SettingsOption {
            colorize: option-colorize;
            has-icon: true;
            icons: [@image-url("../../res/icons/settings/dark.svg"),@image-url("../../res/icons/settings/light.svg")];
            border-color: option-border-color;
            background: option-bg-color;
            current-icon: dark?0:1;
            option-name: "深色模式";
            HorizontalLayout {
                alignment: end;
                // ComboBox {
                //     current-value: "白色";
                //     width: 125px;
                //     model: ["白色","深色"];
                //     selected => {
                //         dark = self.current-value == "深色";
                //         themes.current-icon = dark?1:0;
                //     }
                // }
                Switch {
                    checked: false;
                    toggled => {
                        dark = self.checked;
                    }
                }
            }
        }
    }
}