import { Translator,TranslatorData } from "./translator.slint";

export global en {
    in property <string> version:TranslatorData.version;
    in property <string> username:TranslatorData.username;
    in-out property <Translator> lang: {
        title: @tr("OpenFrp Launcher {0}",version),
        menu: "Menu",
        home:"Home",
        tunnel:"Tunnel",
        console:"Console",
        settings: "Settings",
        opacity: "Opacity",
        language: "Language",
        themes: "Themes",
        dark_mode: "Dark",
        light_mode: "Light",
        login_tips: @tr("Hello, {0}",username),
        no_login_tips: @tr("Please login"),
        default_username:"Please login",
        login: "Login",
        email: "Email",
        password: "Password",
        email_placeholder: "Enter email",
        password_placeholder: "Enter password",
        logging_in: "Logging in...",
    };
}