import { Translator,TranslatorData } from "./translator.slint";

export global zh_hans {
    in property <string> version:TranslatorData.version;
    in property <string> username:TranslatorData.username;
    in-out property <Translator> lang: {
        title: @tr("OpenFrp 启动器 {0}",version),
        menu: "菜单",
        home:"首页",
        tunnel:"隧道",
        console:"控制台",
        settings: "设置",
        opacity: "不透明度",
        language: "语言",
        themes: "主题",
        dark_mode: "深色",
        light_mode: "浅色",
        login_tips: @tr("你好，{0}",username),
        no_login_tips: @tr("你还没有登录哦"),
        default_username:"请先登录",
        login: "登录",
        email: "邮箱",
        password: "密码",
        email_placeholder: "请输入邮箱",
        password_placeholder: "请输入密码",
        logging_in:"登录中...",
    };
}